apps/team/urls.py
from django.urls import path

from .api import create_checkout_session, stripe_webhook
from .views import add, team, edit, activate_team, invite, plans, plans_thankyou


app_name = "team"


urlpatterns = [
    path("add/", add, name="add"),
    path("edit/", edit, name="edit"),
    path("invite/", invite, name="invite"),
    path("plans/", plans, name="plans"),
    path("plans/plans_thankyou/", plans_thankyou, name="plans"),
    path("<int:team_id>/", team, name="team"),
    path("activate_team/<int:team_id>/", activate_team, name="activate_team"),
    path("api/stripe_webhook/", stripe_webhook, name="stripe_webhook"),
    path(
        "api/create_checkout_session/",
        create_checkout_session,
        name="create_checkout_session",
    ),
]

apps/userprofile/urls.py
from django.urls import path
from .views import myaccount, edit_profile, accept_invitation


urlpatterns = [
    path('', myaccount, name='myaccount'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('accept_invitation/', accept_invitation, name='accept_invitation'),
]

ttt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from apps.core.views import frontpage, privacy, terms, plans, signup

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", frontpage, name="frontpage"),
    path("privacy/", privacy, name="privacy"),
    path("terms/", terms, name="terms"),
    path("plans/", plans, name="plans"),
    path("signup/", signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="core/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("dashboard/", include("apps.dashboard.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/team/models.py
from django.contrib.auth.models import User
from django.db import models


class Plan(models.Model):
    title = models.CharField(max_length=255)
    max_projects_per_team = models.IntegerField(default=0)
    max_members_per_team = models.IntegerField(default=0)
    max_tasks_per_project = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.title 
    
    
class Team(models.Model):

    ACTIVE = 'active'
    DELETED = 'deleted'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted')
    )

    PLAN_ACTIVE = 'active'
    PLAN_CANCELED = 'canceled'

    CHOICES_PLAN_STATUS = (
        (PLAN_ACTIVE, 'Active'),
        (PLAN_CANCELED, 'Canceled')
    )

    title = models.CharField(max_length=255)
    members = models.ManyToManyField(User, related_name='teams')
    created_by = models.ForeignKey(User, related_name='created_teams', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=ACTIVE)
    plan = models.ForeignKey(Plan, related_name='teams', on_delete=models.CASCADE)
    plan_end_date = models.DateTimeField(blank=True, null=True)
    plan_status = models.CharField(max_length=20, choices=CHOICES_PLAN_STATUS, default=PLAN_ACTIVE)
    stripe_customer_id = models.CharField(max_length=255, blank=True, null=True)
    stripe_subscription_id = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering = ['title']
    
    def __str__(self):
        return self.title
    

class Invitation(models.Model):
    #
    # Status

    INVITED = 'invited'
    ACCEPTED = 'accepted'

    CHOICES_STATUS = (
        (INVITED, 'Invited'),
        (ACCEPTED, 'Accepted')
    )

    team = models.ForeignKey(Team, related_name='invitations', on_delete=models.CASCADE)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=INVITED)
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

apps/userprofile/models.py
from django.contrib.auth.models import User
from django.db import models


class Userprofile(models.Model):
    user = models.OneToOneField(
        User, related_name="userprofile", on_delete=models.CASCADE
    )
    active_team_id = models.IntegerField(default=0)
    avatar = models.ImageField(upload_to='uploads/avatars/', blank=True, null=True)

    def get_avatar(self):
        if self.avatar:
            return self.avatar.url
        else:
            return '/static/images/avatar.png'
        
    def __str__(self):
        return f"{self.id} - {self.user.username} - {self.user.id}"

apps/userprofile/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect

from apps.team.models import Invitation, Team
from apps.team.utilities import send_invitation_accepted


@login_required
def myaccount(request):
    teams = request.user.teams.exclude(pk=request.user.userprofile.active_team_id)
    return render(request, "userprofile/myaccount.html", {"teams": teams})


@login_required
def edit_profile(request):
    if request.method == "POST":
        request.user.first_name = request.POST.get("first_name", "")
        request.user.last_name = request.POST.get("last_name", "")
        request.user.email = request.POST.get("email", "")
        request.user.save()

        if request.FILES:
            avatar = request.FILES["avatar"]
            userprofile = request.user.userprofile
            userprofile.avatar = avatar
            userprofile.save()

        messages.info(request, "The changes was saved")

        return redirect("myaccount")

    return render(request, "userprofile/edit_profile.html")


@login_required
def accept_invitation(request):
    if request.method == "POST":
        code = request.POST.get("code")

        invitations = Invitation.objects.filter(code=code, email=request.user.email)

        if invitations:
            invitation = invitations[0]
            invitation.status = Invitation.ACCEPTED
            invitation.save()

            team = invitation.team
            team.members.add(request.user)
            team.save()

            userprofile = request.user.userprofile
            userprofile.active_team_id = team.id
            userprofile.save()

            messages.info(request, "Invitation accepted")

            send_invitation_accepted(team, invitation)

            return redirect("team:team", team_id=team.id)
        else:
            messages.info(request, "Invitation was not found")
    else:
        return render(request, "userprofile/accept_invitation.html")

apps/userprofile/templates/userprofile/accept_invitation.html
{% extends 'core/base.html' %}

{% block title %}Accept invitation | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'accept_invitation' %}" aria-current="page">Accept invitation</a></li>
        </ul>
    </nav>

    <div class="columns">
        <div class="column is-4">
            <h1 class="title">Accept invitation</h1>

            <form method="post" action=".">
                {% csrf_token %}

                <div class="field">
                    <label>Code (from e-mail)</label>

                    <div class="control">
                        <input type="text" name="code" id="id_code" class="input">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

apps/userprofile/templates/userprofile/edit_profile.html
{% extends 'core/base.html' %}

{% block title %}Edit profile | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'edit_profile' %}" aria-current="page">Edit profile</a></li>
        </ul>
    </nav>

    <div class="columns">
        <div class="column is-4">
            <h1 class="title">Edit profile</h1>

            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}

                <div class="field">
                    <label>First name</label>

                    <div class="control">
                        <input type="text" name="first_name" id="first_name" class="input"{% if request.user.first_name %} value="{{ request.user.first_name }}"{% endif %}>
                    </div>
                </div>

                <div class="field">
                    <label>Last name</label>

                    <div class="control">
                        <input type="text" name="last_name" id="last_name" class="input"{% if request.user.last_name %} value="{{ request.user.last_name }}"{% endif %}>
                    </div>
                </div>

                <div class="field">
                    <label>E-mail</label>

                    <div class="control">
                        <input type="text" name="email" id="email" class="input"{% if request.user.email %} value="{{ request.user.email }}"{% endif %}>
                    </div>
                </div>

                <div class="field">
                    <label>Avatar</label>

                    <figure class="image is-64x64">
                        <img src="{{ request.user.userprofile.get_avatar }}">
                    </figure>

                    <div class="control mt-2">
                        <input type="file" name="avatar" id="id_avatar" class="input">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Save changes</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

apps/userprofile/templates/userprofile/myaccount.html
{% extends 'core/base.html' %}

{% block title %}My account | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li class="is-active"><a href="{% url 'myaccount' %}" aria-current="page">My account</a></li>
        </ul>
    </nav>

    <div class="columns">
        <div class="column is-6">
            <div class="media mb-4">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <img src="{{ user.userprofile.get_avatar }}">
                    </figure>
                </div>

                <div class="media-content">
                    <p class="title is-3">{% firstof user.get_full_name user.username %}</p>
                    <p class="subtitle is-6">{{ user.email }}</p>
                </div>
            </div>
            <a href="{% url 'edit_profile' %}" class="button is-info">
                <span class="icon"><i class="far fa-edit"></i></span>
                <span>Edit profile</span></a>
            <a href="{% url 'logout' %}" class="button is-danger">
                <span class="icon"><i class="fas fa-sign-out-alt"></i></span>
                <span>Log out</span>
            </a>


        </div>
    </div>

    <hr>

    {% if invitations %}
    <div class="notification is-info">
        <h2 class="subtitle">You have pending invitations</h2>

        {% for invitation in invitations %}
            <a href="{% url 'accept_invitation' %}">{{ invitation.team.title }}</a>
        {% endfor %}
    </div>
    {% endif %}

    <div class="columns">
        <div class="column is-12">
            <h2 class="subtitle">Teams</h2>

            <a href="{% url 'team:add' %}" class="button is-success">Add team</a>
        </div>
    </div>

    <div class="columns">
        {% if active_team %}
            <div class="column is-4">
                <div class="notification has-background-success-light">
                    <h3 class="is-size-5">{{ active_team.title }}{% if active_team.created_by == request.user %}(Owner){% else %}(Member){% endif %}</h3>
                
                    <h3 class="is-size-6">SHOW PLAN HERE</h3>

                    <hr>

                    <a href="{% url 'team:team' active_team.id %}" class="button is-success">Details</a>

                    {% if active_team.created_by == request.user %}
                        <a href="#" class="button is-info">Invite users</a>
                    {% endif %}
                </div>
            </div>
        {% endif %}

        {% for team in teams %}
            <div class="column is-4">
                <div class="notification">
                    <h3 class="is-size-5">{{ team.title }}{% if team.created_by == request.user %}(Owner){% else %}(Member){% endif %}</h3>
                    <h3 class="is-size-6">SHOW PLAN HERE</h3>
                    <hr>
                    <a href="{% url 'team:team' active_team.id %}" class="button is-success">Details</a>
                    <a href="{% url 'team:activate_team' team.id %}" class="button is-info">Activate</a>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}