apps/project/urls.py
from django.urls import path


from .api import api_start_timer, api_stop_timer, api_discard_timer, api_get_tasks
from .views import (
    projects,
    project,
    edit_project,
    task,
    edit_task,
    edit_entry,
    delete_entry,
    delete_untracked_entry,
    track_entry,
)

app_name = "project"

urlpatterns = [
    path("", projects, name="projects"),
    path("<int:project_id>/", project, name="project"),
    path("<int:project_id>/edit/", edit_project, name="edit_project"),
    path("<int:project_id>/<int:task_id>/edit/", task, name="task"),
    path("<int:project_id>/<int:task_id>/", edit_task, name="edit_task"),
    path(
        "<int:project_id>/<int:task_id>/<int:entry_id>/edit/",
        edit_entry,
        name="edit_entry",
    ),
    path(
        "<int:project_id>/<int:task_id>/<int:entry_id>/delete/",
        delete_entry,
        name="delete_entry",
    ),
    path(
        "<int:entry_id>/delete_untracked_entry/",
        delete_untracked_entry,
        name="delete_untracked_entry",
    ),
    path("track_entry/<int:entry_id>/", track_entry, name="track_entry"),
    path("api/start_timer/", api_start_timer, name="api_start_timer"),
    path("api/stop_timer/", api_stop_timer, name="api_stop_timer"),
    path("api/discard_timer/", api_discard_timer, name="api_discard_timer"),
    path("api/get_tasks/", api_get_tasks, name="api_get_tasks"),
]

apps/team/urls.py
from django.urls import path

from .api import create_checkout_session, stripe_webhook
from .views import add, team, edit, activate_team, invite, plans, plans_thankyou


app_name = "team"


urlpatterns = [
    path("add/", add, name="add"),
    path("edit/", edit, name="edit"),
    path("invite/", invite, name="invite"),
    path("plans/", plans, name="plans"),
    path("plans/plans_thankyou/", plans_thankyou, name="plans"),
    path("<int:team_id>/", team, name="team"),
    path("activate_team/<int:team_id>/", activate_team, name="activate_team"),
    path("api/stripe_webhook/", stripe_webhook, name="stripe_webhook"),
    path(
        "api/create_checkout_session/",
        create_checkout_session,
        name="create_checkout_session",
    ),
]

ttt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from apps.core.views import frontpage, privacy, terms, plans, signup

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", frontpage, name="frontpage"),
    path("privacy/", privacy, name="privacy"),
    path("terms/", terms, name="terms"),
    path("plans/", plans, name="plans"),
    path("signup/", signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="core/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("dashboard/", include("apps.dashboard.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/project/models.py
from django.contrib.auth.models import User
from django.db import models

from apps.team.models import Team


class Project(models.Model):
    team = models.ForeignKey(Team, related_name='projects', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)

    created_by = models.ForeignKey(User, related_name='projects', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['title']
    
    def __str__(self):
        return self.title
    
    def registered_time(self):
        return sum(entry.minutes for entry in self.entries.all())
    
    def num_tasks_todo(self):
        return self.tasks.filter(status=Task.TODO).count()
    

class Task(models.Model):
    TODO = 'todo'
    DONE = 'done'
    ARCHIVED = 'archived'

    CHOICES_STATUS = (
        (TODO, 'Todo'),
        (DONE, 'Done'),
        (ARCHIVED, 'Archived')
    )

    team = models.ForeignKey(Team, related_name='tasks', on_delete=models.CASCADE)
    project = models.ForeignKey(Project, related_name='tasks', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name='tasks', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=TODO)

    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return self.title
    
    def registered_time(self):
        return sum(entry.minutes for entry in self.entries.all())
    
    
class Entry(models.Model):
    team = models.ForeignKey(Team, related_name='entries', on_delete=models.CASCADE)
    project = models.ForeignKey(Project, related_name='entries', on_delete=models.CASCADE, blank=True, null=True)
    task = models.ForeignKey(Task, related_name='entries', on_delete=models.CASCADE, blank=True, null=True)
    minutes = models.IntegerField(default=0)
    is_tracked = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='entries', on_delete=models.CASCADE)
    created_at = models.DateTimeField()

    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        if self.task:
            return '%s - %s' % (self.task.title, self.created_at)
        
        return '%s' % self.created_at

apps/project/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .models import Project, Task, Entry
from apps.team.models import Team


@login_required
def projects(request):
    team = get_object_or_404(
        Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE
    )
    projects = team.projects.all()

    if request.method == "POST":
        title = request.POST.get("title")

        if title:
            Project.objects.create(team=team, title=title, created_by=request.user)
            messages.info(request, "The project was added!")
            return redirect("project:projects")

    return render(
        request, "project/projects.html", {"team": team, "projects": projects}
    )


@login_required
def project(request, project_id):
    team = get_object_or_404(
        Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE
    )
    project = get_object_or_404(Project, team=team, pk=project_id)

    if request.method == "POST":
        title = request.POST.get("title")

        if title:
            Task.objects.create(
                team=team, project=project, created_by=request.user, title=title
            )
            messages.info(request, "The task was added!")
            return redirect("project:project", project_id=project.id)

    tasks_todo = project.tasks.filter(status=Task.TODO)
    tasks_done = project.tasks.filter(status=Task.DONE)

    return render(
        request,
        "project/project.html",
        {
            "team": team,
            "project": project,
            "tasks_todo": tasks_todo,
            "tasks_done": tasks_done,
        },
    )


@login_required
def edit_project(request, project_id):
    team = get_object_or_404(
        Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE
    )
    project = get_object_or_404(Project, team=team, pk=project_id)

    if request.method == "POST":
        title = request.POST.get("title")

        if title:
            project.title = title
            project.save()

            messages.info(request, "The changes was saved!")

            return redirect("project:project", project_id=project.id)

    return render(
        request, "project/edit_project.html", {"team": team, "project": project}
    )


@login_required
def task(request, project_id, task_id):
    team = get_object_or_404(
        Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE
    )
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)

    if request.method == "POST":
        hours = int(request.POST.get("hours", 0))
        minutes = int(request.POST.get("minutes", 0))
        date = "%s %s" % (request.POST.get("date"), datetime.now().time())
        minutes_total = (hours * 60) + minutes

        entry = Entry.objects.create(
            team=team,
            project=project,
            task=task,
            minutes=minutes_total,
            created_by=request.user,
            created_at=date,
            is_tracked=True,
        )

    return render(
        request,
        "project/task.html",
        {"today": datetime.today(), "team": team, "project": project, "task": task},
    )


@login_required
def edit_task(request, project_id, task_id):
    team = get_object_or_404(
        Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE
    )
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)

    if request.method == "POST":
        title = request.POST.get("title")
        status = request.POST.get("status")
        if title:
            task.title = title
            task.status = status
            task.save()
            messages.info(request, "The changes was saved!")
            return redirect("project:task", project_id=project.id, task_id=task.id)

    return render(
        request,
        "project/edit_task.html",
        {"team": team, "project": project, "task": task},
    )


@login_required
def edit_entry(request, project_id, task_id, entry_id):
    team = get_object_or_404(
        Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE
    )
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)

    if request.method == "POST":
        hours = int(request.POST.get("hours", 0))
        minutes = int(request.POST.get("minutes", 0))

        date = "%s %s" % (request.POST.get("date"), datetime.now().time())

        entry.created_at = date
        entry.minutes = (hours * 60) + minutes
        entry.save()

        messages.info(request, "The changes was saved!")

        return redirect("project:task", project_id=project.id, task_id=task.id)

    hours, minutes = divmod(entry.minutes, 60)

    context = {
        "team": team,
        "project": project,
        "task": task,
        "entry": entry,
        "hours": hours,
        "minutes": minutes,
    }

    return render(request, "project/edit_entry.html", context)


@login_required
def delete_entry(request, project_id, task_id, entry_id):
    team = get_object_or_404(
        Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE
    )
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)
    entry.delete()

    messages.info(request, "The entry was deleted!")

    return redirect("project:task", project_id=project.id, task_id=task.id)


@login_required
def delete_untracked_entry(request, entry_id):
    team = get_object_or_404(
        Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE
    )
    entry = get_object_or_404(Entry, pk=entry_id, team=team)
    entry.delete()

    messages.info(request, "The entry was deleted!")

    return redirect("dashboard")


@login_required
def track_entry(request, entry_id):
    team = get_object_or_404(
        Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE
    )
    entry = get_object_or_404(Entry, pk=entry_id, team=team)
    projects = team.projects.all()

    if request.method == "POST":
        hours = int(request.POST.get("hours", 0))
        minutes = int(request.POST.get("minutes", 0))
        project = request.POST.get("project")
        task = request.POST.get("task")

        if project and task:
            entry.project_id = project
            entry.task_id = task
            entry.minutes = (hours * 60) + minutes
            entry.created_at = "%s %s" % (
                request.POST.get("date"),
                entry.created_at.time(),
            )
            entry.is_tracked = True
            entry.save()

            messages.info(request, "The time was tracked")

            return redirect("dashboard")

    hours, minutes = divmod(entry.minutes, 60)

    context = {
        "hours": hours,
        "minutes": minutes,
        "team": team,
        "projects": projects,
        "entry": entry,
    }

    return render(request, "project/track_entry.html", context)

apps/project/templates/project/edit_project.html
{% extends 'core/base.html' %}

{% block title %}Edit project | {% endblock %}

{% block content %}
    <div id="project-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="#">Dashboard</a></li>
                <li><a href="{% url 'project:projects' %}">Projects</a></li>
                <li><a href="{% url 'project:project' project.id %}">{{ project.title }}</a></li>
                <li class="is-active"><a href="{% url 'project:edit_project' project.id %}" aria-current="page">Edit project</a></li>
            </ul>
        </nav>

        <div class="columns">
            <div class="column">
                <h1 class="title">Edit project</h1>
            </div>
        </div>

        <div class="columns">
            <div class="column is-4">
                <form method="post" action=".">
                    {% csrf_token %}

                    <div class="field">
                        <label>Title</label>

                        <div class="control">
                            <input type="text" name="title" id="id_title" class="input" value="{{ project.title }}">
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            <button class="button is-success">Save changes</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

apps/project/templates/project/edit_task.html
{% extends 'core/base.html' %}

{% block title %}Edit task | {% endblock %}

{% block content %}
    <div id="project-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="#">Dashboard</a></li>
                <li><a href="{% url 'project:projects' %}">Projects</a></li>
                <li><a href="{% url 'project:project' project.id %}">{{ project.title }}</a></li>
                <li class="is-active"><a href="{% url 'project:edit_task' project.id task.id %}" aria-current="page">Edit task</a></li>
            </ul>
        </nav>

        <div class="columns">
            <div class="column">
                <h1 class="title">Edit task</h1>
            </div>
        </div>

        <div class="columns">
            <div class="column is-4">
                <form method="post" action=".">
                    {% csrf_token %}

                    <div class="field">
                        <label>Title</label>

                        <div class="control">
                            <input type="text" name="title" id="id_title" class="input" value="{{ task.title }}">
                        </div>
                    </div>

                    <div class="field">
                        <label>Status</label>
                        <div class="control">
                            <div class="select">
                                <select name="status" id="id_status">
                                    <option value="todo"{% if task.status == 'todo' %} selected{% endif %}>Todo</option>
                                    <option value="done"{% if task.status == 'done' %} selected{% endif %}>Done</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            <button class="button is-success">Save changes</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

apps/project/templates/project/project.html
{% extends 'core/base.html' %}
{% load dashboardextras %}

{% block title %}{{ project.title }} | {% endblock %}

{% block content %}
    <div id="project-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="#">Dashboard</a></li>
                <li><a href="{% url 'project:projects' %}">Projects</a></li>
                <li class="is-active"><a href="{% url 'project:project' project.id %}" aria-current="page">{{ project.title }}</a></li>
            </ul>
        </nav>

        <div class="columns">
            <div class="column">
                <h1 class="title">{{ project.title }}</h1>

                <div class="buttons">
                    {% if team.plan.max_tasks_per_project > project.tasks.count %}
                    <a @click="showAddTaskModal = !showAddTaskModal" class="button is-success">Add task</a>
                    {% else %}
                    <div class="notification is-warning">
                        This team has reached the limit of tasks for this project.<br>
                            <a href="{% url 'team:plans' %}">Upgrade plan</a>
                            Contact your team owner...
                    </div>
                    <a href="{% url 'project:edit_project' project.id %}" class="button is-warning">Edit project</a>
                    {% endif %}
            </div>
        </div>

        {% if not tasks_todo and not tasks_done %}
            <div class="columns">
                <div class="column is-3">
                    <div class="notification">
                        <p>No tasks yet...</p>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="columns is-multiline">
            {% if tasks_todo %}
                <div class="column is-12">
                    <h2 class="is-size-4">Todo</h2>
                </div>

                {% for task in tasks_todo %}
                    <div class="column is-4">
                        <div class="notification">
                            <h3 class="is-size-5">{{ task.title }}</h3>

                            <p>Registered time: {{ task.registered_time|format_minutes }}</p>

                            <hr>

                            <a href="{% url 'project:task' project.id task.id %}" class="button is-success">Details</a>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

            {% if tasks_done %}
                <div class="column is-12">
                    <h2 class="is-size-4">Done</h2>
                </div>

                {% for task in tasks_done %}
                    <div class="column is-4">
                        <div class="notification">
                            <h3 class="is-size-5">{{ task.title }}</h3>

                            <p>Registered time: {{ task.registered_time }}</p>

                            <hr>

                            <a href="{% url 'project:task' project.id task.id %}" class="button is-success">Details</a>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        <div class="modal" :class="{'is-active': showAddTaskModal }">
            <div class="modal-background"></div>

            <form method="post" action="." @submit="validateForm">
                {% csrf_token %}

                <div class="modal-card">
                    <div class="modal-card-head">
                        <p class="modal-card-title">Add task</p>
                    </div>

                    <div class="modal-card-body">
                        <div class="field">
                            <label>Title</label>
                            <div class="control">
                                <input type="text" name="title" id="id_title" v-model="title" class="input">
                            </div>
                        </div>

                        <div class="notification is-danger" v-if="showError">
                            The title field is missing!
                        </div>
                    </div>

                    <footer class="modal-card-foot">
                        <button class="button is-success">Submit</button>
                        <button class="button" @click="showAddTaskModal = !showAddTaskModal">Cancel</button>
                    </footer>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const ProjectApp = {
            data() {
                return {
                    showAddTaskModal: false,
                    title: '',
                    showError: false
                }
            },
            delimiters: ['[[', ']]'],
            methods: {
                validateForm(e) {
                    if (this.title) {
                        return true
                    }

                    this.showError = true

                    e.preventDefault()

                    return false
                }
            }
        }

        Vue.createApp(ProjectApp).mount('#project-app')
    </script>
{% endblock %}

apps/project/templates/project/projects.html
{% extends 'core/base.html' %}
{% load dashboardextras %}

{% block title %}Projects | {% endblock %}

{% block content %}
    <div id="projects-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="#">Dashboard</a></li>
                <li class="is-active"><a href="#" aria-current="page">Projects</a></li>
            </ul>
        </nav>

        <div class="columns">
            <div class="column is-4">
                <h1 class="title">Projects</h1>
                {% if team.plan.max_projects_per_team > team.projects.count %}
                    <a @click="showAddProjectModal = !showAddProjectModal" class="button is-success">Add project</a>
                {% else %}
                <div class="notification is-warning">
                    This team has reached the limit of projects.<br>

                    {% if team.created_by == request.user %}
                        <a href="{% url 'team:plans' %}">Upgrade plan</a>
                    {% else %}
                        Contact your team owner...
                    {% endif %}
                </div>
                {% endif %} 
            </div>
        </div>
        <div class="columns">
            {% for project in projects %}
                <div class="column is-3">
                    <div class="notification">
                        <h2 class="is-size-5">{{ project.title }}</h2>
                        <p class="is-size-7">Registered time: {{ project.registered_time|format_minutes }}</p>
                        <p class="is-size-7">Tasks: {{ project.num_tasks_todo }}</p>

                        <hr>

                        <a href="{% url 'project:project' project.id %}" class="button is-success">Details</a>
                    </div>
                </div>
            {% empty %}
                <div class="column is-3">
                    <div class="notification">
                        No projects yet...
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="modal" :class="{'is-active': showAddProjectModal}">
            <div class="modal-background"></div>

            <form method="post" action="." @submit="validateForm">
                {% csrf_token %}

                <div class="modal-card">
                    <div class="modal-card-head">
                        <p class="modal-card-title">Add project</p>
                    </div>

                    <div class="modal-card-body">
                        <div class="field">
                            <label>Title</label>
                            <div class="control">
                                <input type="text" name="title" id="id_title" v-model="title" class="input">
                            </div>
                        </div>

                        <div class="notification is-danger" v-if="showError">
                            The title field is missing!
                        </div>
                    </div>

                    <footer class="modal-card-foot">
                        <button class="button is-success">Submit</button>
                        <button class="button" @click="showAddProjectModal = !showAddProjectModal">Cancel</button>
                    </footer>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const ProjectsApp = {
            data() {
                return {
                    showAddProjectModal: false,
                    title: '',
                    showError: false
                }
            },
            delimiters: ['[[', ']]'],
            methods: {
                validateForm(e) {
                    if (this.title) {
                        return true
                    }

                    this.showError = true

                    e.preventDefault()

                    return false
                }
            }
        }

        Vue.createApp(ProjectsApp).mount('#projects-app')
    </script>
{% endblock %}

apps/project/templates/project/task.html
{% extends 'core/base.html' %}
{% load dashboardextras %}

{% block title %}{{ task.title }} | {% endblock %}

{% block content %}
    <div id="project-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="#">Dashboard</a></li>
                <li><a href="{% url 'project:projects' %}">Projects</a></li>
                <li><a href="{% url 'project:project' project.id %}">{{ project.title }}</a></li>
                <li class="is-active"><a href="{% url 'project:task' project.id task.id %}" aria-current="page">{{ task.title }}</a></li>
            </ul>
        </nav>

        <div class="columns">
            <div class="column">
                <h1 class="title">{{ task.title }} ({{ task.get_status_display }})</h1>

                <a href="{% url 'project:edit_task' project.id task.id %}" class="button is-warning">Edit task</a>
            
                <h2 class="subtitle mt-6">Register time</h2>

                <form method="post" action=".">
                    {% csrf_token %}

                    <div class="field is-grouped">
                        <div class="control">
                            <div class="select">
                                <select name="hours">
                                    <option value="0">0h</option>
                                    {% for i in "x"|rjust:"10" %}
                                        <option value="{{ forloop.counter }}">{{ forloop.counter }}h</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="control">
                            <div class="select">
                                <select name="minutes">
                                    <option value="0">0m</option>
                                    {% for i in "x"|rjust:"59" %}
                                        <option value="{{ forloop.counter }}">{{ forloop.counter }}m</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <label>Date</label>

                        <div class="control">
                            <input type="date" id="id_date" name="date" class="input" value="{{ today|date:'Y-m-d' }}" placeholder="yyyy-mm-dd">
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            <button class="button is-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="columns">
            <div class="column is-12">
                <hr>

                <h2 class="subtitle">Logged entries</h2>

                {% if task.entries.all %}
                    <table class="table is-fullwidth" style="text-align: left;">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>User</th>
                                <th>Time</th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for entry in task.entries.all %}
                                <tr>
                                    <td>{{ entry.created_at }}</td>
                                    <td>{% firstof entry.created_by.get_full_name entry.created_by.username %}</td>
                                    <td>{{ entry.minutes|format_minutes }}</td>
                                    <td>
                                        <a href="{% url 'project:edit_entry' project.id task.id entry.id %}">Edit</a>
                                        <a href="{% url 'project:delete_entry' project.id task.id entry.id %}">Delete</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>

                        <tfoot>
                            <tr>
                                <th colspan="2">Total</th>
                                <th colspan="2">{{ task.registered_time }}</th>
                            </tr>
                        </tfoot>
                    </table>
                {% else %}
                    <p>No entries yet...</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}