apps/team/urls.py
from django.urls import path

from .api import create_checkout_session, stripe_webhook
from .views import add, team, edit, activate_team, invite, plans, plans_thankyou


app_name = "team"


urlpatterns = [
    path("add/", add, name="add"),
    path("edit/", edit, name="edit"),
    path("invite/", invite, name="invite"),
    path("plans/", plans, name="plans"),
    path("plans/plans_thankyou/", plans_thankyou, name="plans"),
    path("<int:team_id>/", team, name="team"),
    path("activate_team/<int:team_id>/", activate_team, name="activate_team"),
    path("api/stripe_webhook/", stripe_webhook, name="stripe_webhook"),
    path(
        "api/create_checkout_session/",
        create_checkout_session,
        name="create_checkout_session",
    ),
]

ttt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from apps.core.views import frontpage, privacy, terms, plans, signup

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", frontpage, name="frontpage"),
    path("privacy/", privacy, name="privacy"),
    path("terms/", terms, name="terms"),
    path("plans/", plans, name="plans"),
    path("signup/", signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="core/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("dashboard/", include("apps.dashboard.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/team/models.py
from django.contrib.auth.models import User
from django.db import models


class Plan(models.Model):
    title = models.CharField(max_length=255)
    max_projects_per_team = models.IntegerField(default=0)
    max_members_per_team = models.IntegerField(default=0)
    max_tasks_per_project = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.title 
    
    
class Team(models.Model):

    ACTIVE = 'active'
    DELETED = 'deleted'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted')
    )

    PLAN_ACTIVE = 'active'
    PLAN_CANCELED = 'canceled'

    CHOICES_PLAN_STATUS = (
        (PLAN_ACTIVE, 'Active'),
        (PLAN_CANCELED, 'Canceled')
    )

    title = models.CharField(max_length=255)
    members = models.ManyToManyField(User, related_name='teams')
    created_by = models.ForeignKey(User, related_name='created_teams', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=ACTIVE)
    plan = models.ForeignKey(Plan, related_name='teams', on_delete=models.CASCADE)
    plan_end_date = models.DateTimeField(blank=True, null=True)
    plan_status = models.CharField(max_length=20, choices=CHOICES_PLAN_STATUS, default=PLAN_ACTIVE)
    stripe_customer_id = models.CharField(max_length=255, blank=True, null=True)
    stripe_subscription_id = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering = ['title']
    
    def __str__(self):
        return self.title
    

class Invitation(models.Model):
    #
    # Status

    INVITED = 'invited'
    ACCEPTED = 'accepted'

    CHOICES_STATUS = (
        (INVITED, 'Invited'),
        (ACCEPTED, 'Accepted')
    )

    team = models.ForeignKey(Team, related_name='invitations', on_delete=models.CASCADE)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=INVITED)
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

apps/team/views.py
import datetime
import random
from django.conf import settings

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
import stripe

from apps.team.utilities import send_invitation

from .models import Invitation, Plan, Team


@login_required
def team(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    invitations = team.invitations.filter(status=Invitation.INVITED)

    return render(request, 'team/team.html', {'team': team, 'invitations': invitations})

@login_required
def activate_team(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    userprofile = request.user.userprofile
    userprofile.active_team_id = team.id
    userprofile.save()

    messages.info(request, 'The team was activated')

    return redirect('team:team', team_id=team.id)


@login_required
def add(request):
    if request.method == 'POST':
        title = request.POST.get('title')

        if title:
            team = Team.objects.create(title=title, created_by=request.user)
            team.members.add(request.user)
            team.save()

            userprofile = request.user.userprofile
            userprofile.active_team_id = team.id
            userprofile.save()

            return redirect('myaccount')
    
    return render(request, 'team/add.html')


@login_required
def edit(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE, members__in=[request.user])

    if request.method == 'POST':
        title = request.POST.get('title')
        if title:
            team.title = title
            team.save()
            messages.info(request, 'The changes was saved')
            return redirect('team:team', team_id=team.id)

    return render(request, 'team/edit.html', {'team': team})


@login_required
def invite(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)

    if request.method == 'POST':
        email = request.POST.get('email')

        if email:
            invitations = Invitation.objects.filter(team=team, email=email)

            if not invitations:
                code = ''.join(random.choice('abcdefghijklmnopqrstuvwxyz123456789') for i in range(4))
                invitation = Invitation.objects.create(team=team, email=email, code=code)

                messages.info(request, 'The user was invited')

                send_invitation(email, code, team)

                return redirect('team:team', team_id=team.id)
            else:
                messages.info(request, 'The users has already been invited')

    return render(request, 'team/invite.html', {'team': team})


@login_required
def plans(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    error = ''

    if request.GET.get('cancel_plan', ''):
        try:
            plan_default = Plan.objects.get(is_default=True)

            team.plan = plan_default
            team.plan_status = Team.PLAN_CANCELED
            team.save()

            stripe.api_key = settings.STRIPE_SECRET_KEY
            stripe.Subscription.delete(team.stripe_subscription_id)
        except Exception:
            error = 'Something went wrong with the cancelation. Please try again!'

    context = {
        'team': team,
        'error': error,
        'stripe_pub_key': settings.STRIPE_PUBLISHABLE_KEY
    }

    return render(request, 'team/plans.html', context)


@login_required
def plans_thankyou(request):
    error = ''

    try:
        team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
        stripe.api_key = settings.STRIPE_SECRET_KEY
        subscription = stripe.Subscription.retrieve(team.stripe_subscription_id)
        product = stripe.Product.retrieve(subscription.plan.product)

        team.plan_status = Team.PLAN_ACTIVE
        team.plan_end_date = datetime.fromtimestamp(subscription.current_period_end)
        team.plan = Plan.objects.get(title=product.name)
        team.save()
    except Exception:
        error = 'There something wrong. Please try again!'

    return render(request, 'team/plans_thankyou.html', {'error': error})

apps/team/templates/team/add.html
{% extends 'core/base.html' %}

{% block title %}Add team | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'team:add' %}" aria-current="page">Add team</a></li>
        </ul>
    </nav>

    <div class="columns" id="team-app">
        <div class="column is-4">
            <h1 class="title">Add team</h1>

            <form method="post" action="." @submit="validateForm">
                {% csrf_token %}

                <div class="field">
                    <label>Title</label>

                    <div class="control">
                        <input type="text" name="title" id="id_title" v-model="title">
                    </div>
                </div>

                <div class="notification is-danger" v-if="errors.length">
                    <p v-for="error in errors">[[ error ]]</p>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    const TeamApp = {
        data() {
            return {
                title: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title) {
                    return true
                }

                e.preventDefault()

                this.errors.push('The title field is missing')
                
                return false
            }
        }
    }

    Vue.createApp(TeamApp).mount('#team-app')
</script>
{% endblock %}

apps/team/templates/team/edit.html
{% extends 'core/base.html' %}

{% block title %}Edit team | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'team:edit' %}" aria-current="page">Edit team</a></li>
        </ul>
    </nav>

    <div class="columns" id="team-app">
        <div class="column is-4">
            <h1 class="title">Edit team</h1>

            <form method="post" action="." @submit="validateForm">
                {% csrf_token %}

                <div class="field">
                    <label>Title</label>

                    <div class="control">
                        <input type="text" name="title" id="id_title" class="input" v-model="title">
                    </div>
                </div>

                <div class="notification is-danger" v-if="errors.length">
                    <p v-for="error in errors">[[ error ]]</p>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Save changes</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    const TeamApp = {
        data() {
            return {
                title: '{{ team.title }}',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title) {
                    return true
                }

                e.preventDefault()

                this.errors.push('The title field is missing')
                
                return false
            }
        }
    }

    Vue.createApp(TeamApp).mount('#team-app')
</script>
{% endblock %}

apps/team/templates/team/email_accepted_invitation.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        
        <title>Teams Time Tracker - 3Ts</title>

        <style type="text/css">
            html {
                width: 100%;
            }

            body {
                width: 100%;
                font-family: Arial;
                font-size: 14px;
                background-color: #fff;
                color: #333;
            }

            a {
                color: #111;
            }
        </style>
    </head>

    <body>
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td><h1>3Ts</h1></td>
            </tr>

            <tr>
                <td>
                    <p>{{ invitation.email }} accepted your invitation.</p>
                </td>
            </tr>
        </table>
    </body>
</html>

apps/team/templates/team/email_invitation.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        
        <title>Teams Time Tracker - 3Ts</title>

        <style type="text/css">
            html {
                width: 100%;
            }

            body {
                width: 100%;
                font-family: Arial;
                font-size: 14px;
                background-color: #fff;
                color: #333;
            }

            a {
                color: #111;
            }
        </style>
    </head>

    <body>
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td><h1>3Ts - Invitation to {{ team.title }}</h1></td>
            </tr>

            <tr>
                <td>
                    <p>You ahve been invited to join {{ team.title }}</p>
                    <p>Click the link below to sign up or log in. Your team activation code is {{ code }}</p>
                </td>
            </tr>

            <tr>
                <td>
                    <a href="{{ acceptation_url }}">Accept invitation</a>
                </td>
            </tr>
        </table>
    </body>
</html>

apps/team/templates/team/invite.html
{% extends 'core/base.html' %}

{% block title %}Invite member | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li><a href="{% url 'team:team' team.id %}">{{ team.title }}</a></li>
            <li class="is-active"><a href="{% url 'team:invite' %}" aria-current="page">Invite member</a></li>
        </ul>
    </nav>

    <div class="columns is-multiline" id="invite-app">
        <div class="column is-4">
            <h1 class="title">Invite member</h1>

            <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">[[ error ]]</p>
            </div>
            {% if team.plan.max_members_per_team > team.members.count %}
            <form method="post" action="." @submit="validateForm" novalite>
                {% csrf_token %}

                <div class="field">
                    <label>E-mail</label>

                    <div class="control">
                        <input type="email" name="email" id="id_email" v-model="email" class="input">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Send invitation</button>
                    </div>
                </div>
            </form>
            {% else %}
            <div class="notification is-warning">
                This team has reached the limit of members.<br>

                {% if team.created_by == request.user %}
                    <a href="{% url 'team:plans' %}">Upgrade plan</a>
                {% else %}
                    Contact your team owner...
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    const InviteApp = {
        data() {
            return {
                email: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                if (this.validateEmail(this.email)) {
                    return true
                }

                this.errors = ['The e-mail is not valid']

                e.preventDefault()

                return false
            },
            validateEmail(email) {
                if (/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/.test(email)) {
                    return true
                }

                return false
            }
        }
    }

    Vue.createApp(InviteApp).mount('#invite-app')
</script>
{% endblock %}

apps/team/templates/team/plans.html
{% extends 'core/base.html' %}

{% block title %}Plans | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li><a href="{% url 'team:team' team.id %}">{{ team.title }}</a></li>
            <li class="is-active"><a href="{% url 'team:plans' %}" aria-current="page"></a></li>
        </ul>
    </nav>

    <div class="columns mt-6" id="plans-app">
        <div class="column is-3">
            <div class="card">
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <p class="title is-4">Free</p>
                            <p class="subtitle is-6">$0</p>
                        </div>
                    </div>

                    <div class="content">
                        <ul>
                            <li>3 projects</li>
                            <li>1 member</li>
                            <li>10 tasks per project</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="column is-3">
            <div class="card">
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <p class="title is-4">Basic</p>
                            <p class="subtitle is-6">$5</p>
                        </div>
                    </div>

                    <div class="content">
                        <ul>
                            <li>10 projects</li>
                            <li>15 member</li>
                            <li>30 tasks per project</li>
                        </ul>

                        <hr>

                        {% if team.plan.title == 'Basic' %}
                            <a href="?cancel_plan=true" class="button is-danger">Cancel</a>
                        {% else %}
                            <a @click="subscribe('basic')" class="button is-primary">Start</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="column is-3">
            <div class="card">
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <p class="title is-4">Pro</p>
                            <p class="subtitle is-6">$10</p>
                        </div>
                    </div>

                    <div class="content">
                        <ul>
                            <li>25 projects</li>
                            <li>50 member</li>
                            <li>100 tasks per project</li>
                        </ul>

                        <hr>

                        {% if team.plan.title == 'Pro' %}
                            <a href="?cancel_plan=true" class="button is-danger">Cancel</a>
                        {% else %}
                            <a @click="subscribe('pro')" class="button is-primary">Start</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="column is-3">
            <div class="card">
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <p class="title is-4">Need more?</p>
                            <p class="subtitle is-6">$?</p>
                        </div>
                    </div>

                    <div class="content">
                        <ul>
                            <li>Need more projects?</li>
                            <li>Need more members?</li>
                            <li>Need more tasks?</li>
                        </ul>

                        <hr>

                        <a href="#" class="button is-primary">Contact us</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://js.stripe.com/v3/"></script>
    <script>
        const PlansApp = {
            data() {
                return {
                }
            },
            delimiters: ['[[', ']]'],
            methods: {
                subscribe(plan) {
                    console.log('Subscribe:', plan);

                    const stripe = Stripe('{{ stripe_pub_key }}');

                    fetch('/dashboard/myaccount/teams/api/create_checkout_session/', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                        body: JSON.stringify({
                            'plan': plan
                        })
                    })
                    .then(function(response) {
                        return response.json()
                    })
                    .then(function(session) {
                        console.log(session)
                        return stripe.redirectToCheckout({ sessionId: session.sessionId })
                    })
                    .then(function(result) {
                        if (result.error) {
                            console.log('Error:', result.error.message)
                        }
                    })
                    .catch(function(error) {
                        console.log('Error:', error);
                    });
                }
            }
        }

        Vue.createApp(PlansApp).mount('#plans-app')
    </script>
{% endblock %}

apps/team/templates/team/plans_thankyou.html
{% extends 'core/base.html' %}

{% block title %}Thank you | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li><a href="{% url 'team:plans' %}">Plans</a></li>
            <li class="is-active"><a href="{% url 'team:plans_thankyou' %}" aria-current="page">Thank you</a></li>
        </ul>
    </nav>

    <div class="columns is-multiline">
        <div class="column is-12">
            {% if error %}
                <h1 class="title">Woops, something went wrong</h1>

                Go back to <a href="{% url 'team:plans' %}">plans</a> and try again or <a href="#">contact us</a>!
            {% else %}
                <h1 class="title">Thank you for purchasing a plan</h1>

                <a href="{% url 'dashboard' %}">Go to dashboard</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

apps/team/templates/team/team.html
{% extends 'core/base.html' %}

{% block title %}{{ team.title }} | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'team:team' team.id %}" aria-current="page">{{ team.title }}</a></li>
        </ul>
    </nav>

    <div class="columns is-multiline" id="team-app">
        <div class="column is-4">
            <h1 class="title">{{ team.title }}</h1>

            <p><strong>Current plan: </strong>{{ team.plan.title }}</p>

            {% if team.plan.title != 'Free' %}
                <p><strong>Plan end date: </strong>{{ team.plan_end_date|date:"Y-m-d" }}{% if team.plan_status == 'active' %} (auto renewing){% endif %}</p>
            {% endif %}

            <h2 class="subtitle mt-6">Members</h2>

            {% for member in team.members.all %}
                <p>{{ member.username }}</p>
            {% endfor %}

            {% if request.user == team.created_by %}
                <a href="{% url 'team:invite' %}" class="button is-primary">Invite users</a>
                <a href="{% url 'team:plans' %}" class="button is-success">Change plan</a>
            {% endif %}

            <hr>

            <h2 class="subtitle mt-6">Invited members</h2>

            {% for member in invitations %}
                <p>{{ member.email }} - {{ member.date_sent|timesince }} ago</p>
            {% endfor %}

            
        </div>

        {% if team.created_by == request.user %}
            <div class="column is-12">
                <hr>
                <h3 class="subtitle">Owner actions</h3>
                <a href="{% url 'team:edit' %}" class="button is-warning">Edit team</a>
            </div>
        {% endif %}
    </div>
{% endblock %}